name: DevOps Pipeline

on:
 push:
   branches: [ "main" ]

jobs: 
 build:
   runs-on: windows-latest
   steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup python
      uses: actions/setup python@v5
      with:
       python-version: '3.14'

    - name: Run Python File
      run: python app.py
